<?php
$array_tags = array(
array("id" => "1","tags" => "man","related" => "men,masculine,man"),
array("id" => "2","tags" => "women","related" => "women,woman,female,feminine"),
array("id" => "3","tags" => "best","related" => "best"),
array("id" => "4","tags" => "God","related" => "God,God's,Jehovah"),
array("id" => "5","tags" => "money","related" => "money,funds,moneys"),
array("id" => "6","tags" => "dreams","related" => "dreams,dream,dream't,dreamed"),
array("id" => "7","tags" => "life","related" => "life,living,memories"),
array("id" => "8","tags" => "food","related" => "foods,food,cuisine"),
array("id" => "9","tags" => "sympathy","related" => "sympathy"),
array("id" => "10","tags" => "friendship","related" => "friend,friends,amiable,friendship"),
array("id" => "11","tags" => "power","related" => "power,powers,authority"),
array("id" => "12","tags" => "christmas","related" => "christmas,birth of christ,xmas,yuletide"),
array("id" => "13","tags" => "love","related" => "love,loved,loving"),
array("id" => "14","tags" => "british","related" => "british,uk,britain,england,english,queen elizabeth"),
array("id" => "15","tags" => "technology","related" => "technology,tech,microsoft,facebook,tesla"),
array("id" => "16","tags" => "positive","related" => "positives,positive"),
array("id" => "17","tags" => "success","related" => "success,succeed,successes"),
array("id" => "18","tags" => "business","related" => "business,businesses,investment,wall street,shareholders,shareholding,ipo"),
array("id" => "19","tags" => "investment","related" => "investments,investments,invested,investing,invest,invests,dividends,collateral"),
array("id" => "20","tags" => "mortgage","related" => "mortgage,mortgages,foreclosure"),
array("id" => "21","tags" => "insurance","related" => "insurance,insurances,insure,premium,assurance firms,assurance company,insured"),
array("id" => "22","tags" => "inspirational","related" => "inspirational,inspire,inspired,inspiration,make it in life"),
array("id" => "23","tags" => "social","related" => "social,society,societal,socialite"),
array("id" => "24","tags" => "greatness","related" => "greatness,great,greats,greatest"),
array("id" => "25","tags" => "american","related" => "american,america,donald trump,yankee,chicago,white house,hollywood,obama,bill gates,steve jobs"),
array("id" => "26","tags" => "nigerian","related" => "nigeria,nigerian,naija,9ja,naira"),
array("id" => "27","tags" => "failure","related" => "failure,failures,fail,failed"),
array("id" => "28","tags" => "geek","related" => "geek,geeks,nerd,nerds,nerdy,geeky"),
array("id" => "29","tags" => "wedding","related" => "wedding,wed,bride,groom,bridal,men-in-suit,wedded"),
array("id" => "30","tags" => "time","related" => "time,clock"),
array("id" => "31","tags" => "change","related" => "change,revolution"),
array("id" => "32","tags" => "fear","related" => "fear,afraid,feared"),
array("id" => "33","tags" => "Lord of the Rings","related" => "lord of the rings"),
array("id" => "34","tags" => "Harry Porter","related" => "Harry Porter,Voldemort"),
array("id" => "35","tags" => "mother","related" => "mother,mum,mom,mummy,mama,mamma,mommy"),
array("id" => "36","tags" => "christian","related" => "christ,christianity,pentecostal,Jesus,christians,christian"),
array("id" => "37","tags" => "wisdom","related" => "wise,wisdom"),
array("id" => "38","tags" => "genius","related" => "genius,geniuses,genie"),
array("id" => "39","tags" => "nature","related" => "nature,natural,naturals,natures"),
array("id" => "40","tags" => "liberian","related" => "liberia,liberians,liberian,charles taylor"),
array("id" => "41","tags" => "chinese","related" => "china,chinese,kung fu"),
array("id" => "42","tags" => "leadership","related" => "leadership,leaders,leader"),
array("id" => "43","tags" => "marriage","related" => "marriage,marry,married,marries,divorce,divorced,divorcee,prenup,postnup"),
array("id" => "44","tags" => "science","related" => "science,scientific,scientist"),
array("id" => "45","tags" => "Alzheimer","related" => "alzheimer,alzheimer's,Alzheimers"),
array("id" => "46","tags" => "Easter","related" => "Resurrection of Jesus ,Easter"),
array("id" => "47","tags" => "2013","related" => "twenty-thirteen,twenty thirteen,two thousand and thirteen,2013,'13"),
array("id" => "48","tags" => "9 11","related" => "9-11,September eleven,9 11,11th of September,Sept. 11,11th Sept, World Trade Center Bombing,Sept.,September 11th, 11,September 11,11 Sept.,11 September")
);